// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkInHabit = `-- name: CheckInHabit :exec
INSERT INTO habit_checkins (habit_id, day)
VALUES ($1, $2)
ON CONFLICT (habit_id, day) DO NOTHING
`

type CheckInHabitParams struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) CheckInHabit(ctx context.Context, arg CheckInHabitParams) error {
	_, err := q.db.Exec(ctx, checkInHabit, arg.HabitID, arg.Day)
	return err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateHabitParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit, arg.UserID, arg.Name)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :execrows
DELETE FROM habits
WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, name, created_at FROM habits
WHERE id = $1 AND user_id = $2
`

type GetHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetHabit(ctx context.Context, arg GetHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckinsSince = `-- name: ListCheckinsSince :many
SELECT c.habit_id, c.day
FROM habit_checkins c
JOIN habits h ON h.id = c.habit_id
WHERE h.user_id = $1 AND c.day >= $2
ORDER BY c.day
`

type ListCheckinsSinceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Day    time.Time `json:"day"`
}

type ListCheckinsSinceRow struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) ListCheckinsSince(ctx context.Context, arg ListCheckinsSinceParams) ([]ListCheckinsSinceRow, error) {
	rows, err := q.db.Query(ctx, listCheckinsSince, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinsSinceRow{}
	for rows.Next() {
		var i ListCheckinsSinceRow
		if err := rows.Scan(&i.HabitID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, user_id, name, created_at FROM habits
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListHabits(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncheckHabit = `-- name: UncheckHabit :exec
DELETE FROM habit_checkins
WHERE habit_id = $1 AND day = $2
`

type UncheckHabitParams struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) UncheckHabit(ctx context.Context, arg UncheckHabitParams) error {
	_, err := q.db.Exec(ctx, uncheckHabit, arg.HabitID, arg.Day)
	return err
}
