// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlanByDate = `-- name: GetPlanByDate :one
SELECT id, user_id, plan_date, status, plan_json, error, created_at, updated_at FROM daily_plans
WHERE user_id = $1 AND plan_date = $2
`

type GetPlanByDateParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PlanDate time.Time `json:"plan_date"`
}

func (q *Queries) GetPlanByDate(ctx context.Context, arg GetPlanByDateParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByDate, arg.UserID, arg.PlanDate)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.Status,
		&i.PlanJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, user_id, plan_date, status, plan_json, error, created_at, updated_at FROM daily_plans
WHERE id = $1 AND user_id = $2
`

type GetPlanByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPlanByID(ctx context.Context, arg GetPlanByIDParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, arg.ID, arg.UserID)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.Status,
		&i.PlanJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlanDone = `-- name: SetPlanDone :exec
UPDATE daily_plans
SET status = 'done', plan_json = $2, error = NULL, updated_at = now()
WHERE id = $1
`

type SetPlanDoneParams struct {
	ID       uuid.UUID `json:"id"`
	PlanJson []byte    `json:"plan_json"`
}

func (q *Queries) SetPlanDone(ctx context.Context, arg SetPlanDoneParams) error {
	_, err := q.db.Exec(ctx, setPlanDone, arg.ID, arg.PlanJson)
	return err
}

const setPlanFailed = `-- name: SetPlanFailed :exec
UPDATE daily_plans
SET status = 'failed', error = $2, updated_at = now()
WHERE id = $1
`

type SetPlanFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) SetPlanFailed(ctx context.Context, arg SetPlanFailedParams) error {
	_, err := q.db.Exec(ctx, setPlanFailed, arg.ID, arg.Error)
	return err
}

const setPlanRunning = `-- name: SetPlanRunning :exec
UPDATE daily_plans
SET status = 'running', updated_at = now()
WHERE id = $1
`

func (q *Queries) SetPlanRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPlanRunning, id)
	return err
}

const upsertPlanQueued = `-- name: UpsertPlanQueued :one
INSERT INTO daily_plans (user_id, plan_date, status)
VALUES ($1, $2, 'queued')
ON CONFLICT (user_id, plan_date)
DO UPDATE SET status = 'queued', plan_json = NULL, error = NULL, updated_at = now()
RETURNING id, user_id, plan_date, status, plan_json, error, created_at, updated_at
`

type UpsertPlanQueuedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PlanDate time.Time `json:"plan_date"`
}

func (q *Queries) UpsertPlanQueued(ctx context.Context, arg UpsertPlanQueuedParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, upsertPlanQueued, arg.UserID, arg.PlanDate)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.Status,
		&i.PlanJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
