// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completionTrend = `-- name: CompletionTrend :many
SELECT
    (updated_at AT TIME ZONE 'UTC')::date AS day,
    (COUNT(*))::int                       AS count
FROM tasks
WHERE user_id = $1 AND status = 'completed' AND updated_at >= $2
GROUP BY day
ORDER BY day
`

type CompletionTrendParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CompletionTrendRow struct {
	Day   time.Time `json:"day"`
	Count int32     `json:"count"`
}

func (q *Queries) CompletionTrend(ctx context.Context, arg CompletionTrendParams) ([]CompletionTrendRow, error) {
	rows, err := q.db.Query(ctx, completionTrend, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompletionTrendRow{}
	for rows.Next() {
		var i CompletionTrendRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planCount = `-- name: PlanCount :one
SELECT (COUNT(*))::int AS count
FROM daily_plans
WHERE user_id = $1
`

func (q *Queries) PlanCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, planCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const taskStats = `-- name: TaskStats :one
SELECT
    (COUNT(*))::int                                              AS total,
    (COUNT(*) FILTER (WHERE status = 'completed'))::int          AS completed,
    (COUNT(*) FILTER (WHERE status = 'pending'))::int            AS pending,
    (COUNT(*) FILTER (WHERE priority = 'high'))::int             AS high,
    (COUNT(*) FILTER (WHERE priority = 'medium'))::int           AS medium,
    (COUNT(*) FILTER (WHERE priority = 'low'))::int              AS low,
    (COALESCE(SUM(duration_minutes) FILTER (WHERE status = 'pending'), 0))::int   AS pending_minutes,
    (COALESCE(SUM(duration_minutes) FILTER (WHERE status = 'completed'), 0))::int AS completed_minutes
FROM tasks
WHERE user_id = $1
`

type TaskStatsRow struct {
	Total            int32 `json:"total"`
	Completed        int32 `json:"completed"`
	Pending          int32 `json:"pending"`
	High             int32 `json:"high"`
	Medium           int32 `json:"medium"`
	Low              int32 `json:"low"`
	PendingMinutes   int32 `json:"pending_minutes"`
	CompletedMinutes int32 `json:"completed_minutes"`
}

func (q *Queries) TaskStats(ctx context.Context, userID uuid.UUID) (TaskStatsRow, error) {
	row := q.db.QueryRow(ctx, taskStats, userID)
	var i TaskStatsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Pending,
		&i.High,
		&i.Medium,
		&i.Low,
		&i.PendingMinutes,
		&i.CompletedMinutes,
	)
	return i, err
}
