// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, priority, duration_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, priority, duration_minutes, status, created_at, updated_at
`

type CreateTaskParams struct {
	UserID          uuid.UUID    `json:"user_id"`
	Title           string       `json:"title"`
	Description     string       `json:"description"`
	Priority        TaskPriority `json:"priority"`
	DurationMinutes int32        `json:"duration_minutes"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DurationMinutes,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DurationMinutes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, priority, duration_minutes, status, created_at, updated_at FROM tasks
WHERE id = $1 AND user_id = $2
`

type GetTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DurationMinutes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, priority, duration_minutes, status, created_at, updated_at FROM tasks
WHERE user_id = $1
  AND ($2::task_status IS NULL OR status = $2)
  AND ($3::task_priority IS NULL OR priority = $3)
ORDER BY created_at DESC
`

type ListTasksParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	Status   *TaskStatus   `json:"status"`
	Priority *TaskPriority `json:"priority"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.UserID, arg.Status, arg.Priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DurationMinutes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title            = COALESCE($1, title),
    description      = COALESCE($2, description),
    priority         = COALESCE($3, priority),
    duration_minutes = COALESCE($4, duration_minutes),
    status           = COALESCE($5, status),
    updated_at       = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, title, description, priority, duration_minutes, status, created_at, updated_at
`

type UpdateTaskParams struct {
	Title           *string       `json:"title"`
	Description     *string       `json:"description"`
	Priority        *TaskPriority `json:"priority"`
	DurationMinutes *int32        `json:"duration_minutes"`
	Status          *TaskStatus   `json:"status"`
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DurationMinutes,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DurationMinutes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
